spring:
  datasource:
    url: jdbc:mysql://192.168.126.179:3307/single_test?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: rejoyc
    password: 1qaz@WSX
